### ISSUE TITLE
Bad readme

### ISSUE THREAD

**Issue by seagomezar** [07Gond/npm-global-rm-interactive#1]
Hi Gerson! 🤠🤠🤠
You are the best man!  👏👏👏👏 . Thanks for this fantastic repo!!!! It is always what I dreamed! 🎉🎉🎉🎉🎉🎉

Now, I can't understand what are you doing here man!, Can you at least do a "normal" readme!?

**Comment by 07Gond** [comment]
Hi @seagomezar !
Thanks for your feedback!
This is my first planned task on this repo for today :)
Stay tuned!
