### ISSUE TITLE
Error when "none" option is selected.

### ISSUE THREAD

**Issue by 07Gond** [07Gond/npm-global-rm-interactive#3]
**BUG:**
> Error: Command failed `npm uninstall -g`

**Steps to reproduce:**
- Run the `npm-g-rmi`.
- Choose the 'none' option.

![image](https://user-images.githubusercontent.com/2708687/45332894-e33caa80-b538-11e8-8605-66eb1ef80661.png)

**Comment by mzavaletavargas** [comment]
I have tested on Windows 10 Home, Version 1803 and can't replicate this error, probably this is related to other operating systems, 👍 .
